### ISSUE TITLE
    Unable to run command 'CopyStringsFile LFImagePickerController.strings' - this target might include its own product.

### ISSUE THREAD

**Issue by zinwalin** [Qson8/asset_pickers#2]
`Running "flutter pub get" in example...                                ⣽
    0.4s
Launching lib/main.dart on iPhone in debug mode...
Warning: Missing build name (CFBundleShortVersionString).
Warning: Missing build number (CFBundleVersion).
Action Required: You must set a build name and number in the pubspec.yaml file version field before submitting to the App Store.
Automatically signing iOS for device deployment using specified development team in Xcode project: Z8SUP49TQ2
Running Xcode build...                                                  
Xcode build done.                                            1.0s
Failed to build iOS app
Error output from Xcode build:
↳
    2020-04-14 13:39:17.450 xcodebuild[46758:4678883]  DTDeviceKit: deviceType from 00008030-000A2C921182802E was NULL
    ** BUILD FAILED **

Xcode's output:
↳
    Unable to run command 'CopyStringsFile LFImagePickerController.strings' - this target might include its own product.

Could not build the precompiled application for the device.

Error launching application on iPhone.`

**Comment by Qson8** [comment]
可能是你flutter环境缓存问题

我是这样处理的：
插件内 ./example 目录下 执行命令 flutter clean 
./example/ios  执行pod install  
直接跑example没问题，可以正常跑起来
用xcode打开Runner.xcworkspace 文件，也可以正常run。
